name: Build Resume

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install TeX Live
        run: sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended texlive-xetex latexmk

      - name: Compile LaTeX document
        run: latexmk -pdf -interaction=nonstopmode resume.tex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: resume.pdf
