name: Build Resume

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Build image
        run: docker build --no-cache --tag resume_img -f Dockerfile .

      - name: Run container
        run: docker run --rm -v "${PWD}:/workspace" resume_img

      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: cv/resume.pdf