name: Publish pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: write  # Даем права на запись в репозиторий

    steps:
      - name: Check out repo
        uses: actions/checkout@v4  # Обновляем checkout до v4

      - name: Build image
        run: docker build --no-cache --tag resume_build -f Dockerfile .

      - name: Run container
        run: docker run --rm -v ${{ github.workspace }}:/workspace resume_build

      - name: Save pdf artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: ${{ github.workspace }}/cv/resume.pdf

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/cv
          destination_dir: cv
          publish_branch: deployed_cv
          keep_files: false
          exclude_assets: '*.aux,*.log,*.out'