name: Build and Publish Resume

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Pull latest changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull --rebase origin main || true

      - name: Build image
        run: docker build --no-cache --tag resume_build -f Dockerfile .

      - name: Run container
        run: docker run --rm -v ${{ github.workspace }}:/workspace resume_build

      - name: Save pdf artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: ${{ github.workspace }}/cv/resume.pdf

      - name: Commit PDF to main
        run: |
          git add cv/resume.pdf
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update resume PDF [skip ci]"
            git push origin main
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4